### ISSUE TITLE
Regional statistics

### ISSUE THREAD

**Issue by jvdhurk** [janderk2/roaddanger.org#4]
Is there any chance to extend thecrashes.org to provide a regional analysis of the data? I'm adding news articles from Aachen/Germany at the moment and at some point there could be enough data that a regional analysis could make sense.

**Comment by janderk2** [comment]
Hi Jan, Thanks for your help. The statistics are at this moment made for each country. Here are German counterparties: https://de.thecrashes.org/statistieken/andere_partij?period=all&country=DE 

I see that you have added crashes around Aachen. It is currently not possible, but I have been thinking about adding a regions option with geo contours. That would allow us to do statistics on a region. Or maybe do reverse geo lookups and add the city to the crash data. That way we could do statistics for cities like London or Aachen. But both will take a bit of programming.

**Comment by jvdhurk** [comment]
Hoi Jan,

thank you for getting back to my question! I'm looking forward to having this feature in the future.

**Comment by janderk2** [comment]
There is now a text search field on the graph pages which allows to search for crashes in Aachen:
https://www.roaddanger.org/statistics/counterparty?period=all&country=DE&search=Aachen
https://www.roaddanger.org/statistics/transportation_modes?period=all&country=DE&search=Aachen

Bit of a cheap trick but better than nothing
