### ISSUE TITLE
Editing accident returns database error

### ISSUE THREAD

**Issue by Achilleshiel** [janderk2/roaddanger.org#7]
[Fietsster overleden na verkeersongeval](https://nl.roaddanger.org/11001/)

I wanted to change unknown vehicle to something that represents a mobile home as best as possible. But the it returned the following  error:

```
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `hetongeluk`.`crashpersons`.`child` at row 1
```

I changed something. But the old unknown vehicle is deleted, and the new vehicle is not added.

On further inspection, I cannot add an accident. I Added the HAR file as txt.
[nl.roaddanger.org.har.txt](https://github.com/janderk2/roaddanger.org/files/9008890/nl.roaddanger.org.har.txt).

It is possible to reproduce this in my Vivaldi (chromium) and Firefox browser.

**Comment by janderk2** [comment]
Fixed in latest version
